name: Test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout Repository
        uses: actions/checkout@v4

      - name: 🤖 Install Clang/LLVM
        run: |
          sudo apt-get update
          sudo apt-get install clang llvm libclang-dev

      - name: 🧪 Test
        run: cargo test
